#file: noinspection undefined
spring:
  profiles:
    active: ${env:dev}
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    properties:
      topic:
        model: ${KAFKA_USERNAME}-model
        nick: ${KAFKA_USERNAME}-nick
        user: ${KAFKA_USERNAME}-user
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
    producer:
      properties:
        enable:
          idempotence: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      auto-offset-reset: latest
      group-id: ${KAFKA_USERNAME}-${env:dev}
  security:
    allowed:
      origins: ${ALLOWED_ORIGINS:""}
    jwt:
      token:
        expire: 86400000
        secret: fWVI7z4dDN6bWG5XNPH7jqPRjWbvbD5n
    oauth2:
      authorized:
        redirectUris: ${AUTH_REDIRECT_URIS}
      client:
        registration:
          google:
            clientId: ${GG_CLIENT_ID}
            clientSecret: ${GG_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: gallery
logging:
  level:
    root: info
