spring:
  profiles:
    active: ${env:local}
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  servlet:
    context-path: /api
logging:
  level:
    root: info
