name: Build

on:
  push:
    branches: [ "master", "staging", "dev" ]
  pull_request:
    branches: [ "master", "staging", "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        env:
          REGISTRY_USER: ${{secrets.REGISTRY_USER}}
          REGISTRY_TOKEN: ${{secrets.REGISTRY_TOKEN}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        with:
          arguments: build
